version: '3.4'

services:
  lap-stack:
    image: webdevops/php-apache-dev:7.4
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
      - DB_LOGIN="root"
      - DB_PSW="myPassw1"
      - DB_HOST="mysql"
      - DB_PORT="3306"
    ports:
      - "8006:80"
    volumes:
      - ./app:/var/www/html:rw,cached

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myPassw1
    volumes:
      - ./sql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8005:8080"